AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:

# Application
  MyApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: 
        ApplicationId: 'arn:aws:serverlessrepo:us-west-2:123456789012:applications/MyApplication'
        SemanticVersion: 1.0.0
      Parameters:
        StringParameter: param-value
        IntegerParameter: 2
  MyApplication2:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/bucketName/template.yaml   

# Connector
  Transform: AWS::Serverless-2016-10-31
    MyTable:
      Type: AWS::Serverless::SimpleTable
    MyFunction:
      Type: AWS::Serverless::Function
      Connectors:
        MyConn:
          Properties:
            Destination:
              Id: MyTable
            Permissions:
              - Write 

# StateMachine - AWS Step Functions
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: sfn/MyStateMachine.asl.json
      Role: 'arn:aws:iam:::role/service/MyRole'
      DefinitionSubstitutions:
        MyFunctionArn: !GetAtt MyFunction.Arn
        MyDDBTable: !Ref ProductTable

# Function - API Gateway and DynamoDB
  GetProductionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProductFunction/target/ProductFunction-1.0.jar
      Handler: ProductFunction.App::handleRequest
      Runtime: java21
      Description: Create a ProductFunction
      MemorySize: 1024
      Timeout: 15
      Tracing: 
        Mode: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable
      Events:
        GetProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get
            # ApiKeyRequired: true

# Function - S3
  MyS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MyS3Function
      Handler: index.handler
      Runtime: java21
      Description: Create a MyS3Function
      MemorySize: 1024
      Timeout: 15
      Policies: 
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Layers:
        - arn:aws:123456:layer:aws-sdk:6
      Environment:
        Variables:
          TABLE_NAME: !Ref ProductTable
      Events:
        MyS3Event:
          Type: S3
          Properties: 
            Bucket: !Ref S3Bucket
            Events:
              - s3:ObjectCreated:*

# SimpleTable
  ProductTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: myTable
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        Department: Engineering
        AppType: Serverless

# API
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: swagger.yaml

# HTTP
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        info:
          version: '1.0'
          title:
            Ref: AWS::StackName
        paths:
          "/":
            get:
              security:
              - OpenIdAuth:
                - scope1
                - scope2
              responses: {}
      openapi: 3.0.1
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowOrigins:
          - '*'
        AllowCredentials: true

# (Lambda) Layer version - A Lambda layer is a .zip file archive that contains supplementary code or data
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer
      Description: static data layer for app
      ContentUri: mylayer.zip
      CompatibleRuntimes:
        - java21
      LicenseInfo: Apache 2.0
      RetentionPolicy: Retain

# S3
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: DOC-EXAMPLE-BUCKET

# GraphQL
  MyLambdaFunction:
    Type: AWS::Serverless::Function
  Properties:
    CodeUri: HelloWorldFunction/target/HelloWorld-1.0.jar
    Handler: helloworld.App::handleRequest    
    Runtime: java21

  MyGraphQLAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: MyApi
      SchemaUri: ./gql/schema.gql
      Auth:
        Type: API_KEY
      ApiKeys:
        MyApiKey:
          Description: my api key
      DataSources:
        Lambda:
          MyLambdaDataSource:
            FunctionArn: !GetAtt MyLambdaFunction.Arn
      Functions:
        lambdaInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: MyLambdaDataSource
          CodeUri: ./gql/invoker.js
      Resolvers:
        Mutation:
          addPost:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - lambdaInvoker
        Query:
          getPost:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - lambdaInvoker

Outputs:
  MyGraphQLAPI:
    Description: AppSync API
    Value: !GetAtt MyGraphQLAPI.GraphQLUrl
  MyGraphQLAPIMyApiKey:
    Description: API Key for authentication
    Value: !GetAtt MyGraphQLAPIMyApiKey.ApiKey